'use client'
// import Spline from '@splinetool/react-spline';
// import { useEffect, useState } from 'react';

// export default function VideoDemo({ splineUrl }) {
//   const [key, setKey] = useState(0);

//   // Remount the VideoDemo component when splineUrl changes
//   useEffect(() => {
//     setKey((prevKey) => prevKey + 1);
//   }, [splineUrl]);

//   return (
//     <div key={key}>
//       <Spline scene={splineUrl} priority="high" />
//     </div>
//   );
// }

/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/qD568yXiUwYtR2YJ/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#fefefe']} />
      <group {...props} dispose={null}>
        <scene name="Scene">
          <group
            name="iPhone 14 Pro"
            position={[-3.14, -8.59, 121.86]}
            rotation={[Math.PI / 6, 0, 0]}
            scale={[1, 1.08, 1.06]}
          >
            <group name="Container Rotation" position={[0.1, 7.83, 4.12]} rotation={[0, 0, 0]} scale={1}>
              <group name="Dynamic Island" position={[-11.5, 252.79, 15.88]} scale={1}>
                <group name="Group" position={[11.58, -12.26, 1.28]} rotation={[0, 0, 0]} scale={1}>
                  <mesh
                    name="Ellipse 2"
                    geometry={nodes['Ellipse 2'].geometry}
                    material={materials['Ellipse 2 Material']}
                    castShadow
                    receiveShadow
                    position={[27.83, 0, -0.35]}
                  />
                  <mesh
                    name="Ellipse"
                    geometry={nodes.Ellipse.geometry}
                    material={materials['Ellipse Material']}
                    castShadow
                    receiveShadow
                    position={[27.83, 0, -0.81]}
                  />
                  <mesh
                    name="Rectangle"
                    geometry={nodes.Rectangle.geometry}
                    material={materials['Rectangle Material']}
                    castShadow
                    receiveShadow
                    position={[0, 0, -1.07]}
                  />
                </group>
                <mesh
                  name="Rectangle 5"
                  geometry={nodes['Rectangle 5'].geometry}
                  material={materials['Rectangle 5 Material']}
                  castShadow
                  receiveShadow
                  position={[11.5, 8.79, -0.01]}
                />
              </group>
              <group name="Connectors" position={[0, 0, 0]} scale={1}>
                <mesh
                  name="Rectangle 4"
                  geometry={nodes['Rectangle 4'].geometry}
                  material={materials['Pink Items']}
                  castShadow
                  receiveShadow
                  position={[76.09, 137.8, 0]}
                  rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
                  scale={1}
                />
                <mesh
                  name="Rectangle 3"
                  geometry={nodes['Rectangle 3'].geometry}
                  material={materials['Pink Items']}
                  castShadow
                  receiveShadow
                  position={[-62.45, -137.8, 0]}
                  rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
                  scale={1}
                />
                <mesh
                  name="Rectangle 2"
                  geometry={nodes['Rectangle 2'].geometry}
                  material={materials['Pink Items']}
                  castShadow
                  receiveShadow
                  position={[0, -215.43, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={1}
                />
                <mesh
                  name="Rectangle1"
                  geometry={nodes.Rectangle1.geometry}
                  material={materials['Pink Items']}
                  castShadow
                  receiveShadow
                  position={[0, 210.74, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={1}
                />
              </group>
              <group name="Body-Screen" position={[10.63, 18.95, 0.83]} scale={[1.02, 1.02, 1.04]}>
                <mesh
                  name="Interior_demo (1).mp4"
                  geometry={nodes['Interior_demo (1).mp4'].geometry}
                  material={materials['Interior_demo (1).mp4 Material']}
                  castShadow
                  receiveShadow
                  position={[-10.45, -18.61, 14.55]}
                  rotation={[0, 0, 0]}
                  scale={[0.98, 0.98, 0.96]}
                />
                <mesh
                  name="Back Side"
                  geometry={nodes['Back Side'].geometry}
                  material={materials.Metal}
                  castShadow
                  receiveShadow
                  position={[-10.04, -18.07, -9.56]}
                  rotation={[-Math.PI, 0, Math.PI]}
                  scale={[1.08, 1.08, 1.06]}
                />
                <group name="Left Buttons" position={[-139.66, 74.64, 0.26]} scale={[0.98, 0.98, 0.96]}>
                  <mesh
                    name="Ellipse1"
                    geometry={nodes.Ellipse1.geometry}
                    material={materials['Pink Items']}
                    castShadow
                    receiveShadow
                    position={[-0.02, -262.95, -0.09]}
                    rotation={[0, -Math.PI / 2, 0]}
                    scale={1}
                  />
                  <mesh
                    name="Rectangle 9"
                    geometry={nodes['Rectangle 9'].geometry}
                    material={materials['Rectangle 9 Material']}
                    castShadow
                    receiveShadow
                    position={[0.77, 61.22, -0.26]}
                    rotation={[0, -Math.PI / 2, 0]}
                    scale={[1.04, 1.02, 1.02]}
                  />
                  <mesh
                    name="Rectangle 8"
                    geometry={nodes['Rectangle 8'].geometry}
                    material={materials['Pink Items']}
                    castShadow
                    receiveShadow
                    position={[-1.51, 61.24, 2.07]}
                    rotation={[0, Math.PI / 2, 0]}
                    scale={[1.04, 1.02, 1.02]}
                  />
                  <mesh
                    name="Rectangle 7"
                    geometry={nodes['Rectangle 7'].geometry}
                    material={materials['Pink Items']}
                    castShadow
                    receiveShadow
                    position={[-1.51, 11.96, 0]}
                    rotation={[0, Math.PI / 2, 0]}
                    scale={[1.04, 1.02, 1.02]}
                  />
                  <mesh
                    name="Rectangle 11"
                    geometry={nodes['Rectangle 11'].geometry}
                    material={materials.Metal}
                    castShadow
                    receiveShadow
                    position={[0.24, -241.12, 0]}
                    rotation={[0, -Math.PI / 2, 0]}
                    scale={[1.04, 1.02, 1.02]}
                  />
                  <mesh
                    name="Rectangle 10"
                    geometry={nodes['Rectangle 10'].geometry}
                    material={materials['Pink Items']}
                    castShadow
                    receiveShadow
                    position={[0.54, -241.12, 0]}
                    rotation={[0, -Math.PI / 2, 0]}
                    scale={[1.04, 1.02, 1.02]}
                  />
                  <mesh
                    name="Rectangle 51"
                    geometry={nodes['Rectangle 51'].geometry}
                    material={materials['Pink Items']}
                    castShadow
                    receiveShadow
                    position={[-1.51, -38.91, 0]}
                    rotation={[0, Math.PI / 2, 0]}
                    scale={[1.04, 1.02, 1.02]}
                  />
                </group>
                <group name="Right Buttons" position={[118.57, -3.06, 0.26]} scale={[0.98, 0.98, 0.96]}>
                  <mesh
                    name="Button"
                    geometry={nodes.Button.geometry}
                    material={materials['Pink Items']}
                    castShadow
                    receiveShadow
                    position={[-0.25, -60.23, 0]}
                    rotation={[0, Math.PI / 2, 0]}
                    scale={[1.04, 1.02, 1.02]}
                  />
                  <mesh
                    name="Button1"
                    geometry={nodes.Button1.geometry}
                    material={materials['Pink Items']}
                    castShadow
                    receiveShadow
                    position={[-1.53, 51.46, 0]}
                    rotation={[0, Math.PI / 2, 0]}
                    scale={[1.04, 1.02, 1.02]}
                  />
                </group>
                <mesh
                  name="Metal Border"
                  geometry={nodes['Metal Border'].geometry}
                  material={materials.Metal}
                  castShadow
                  receiveShadow
                  position={[-10.45, -18.61, 13.04]}
                  rotation={[-Math.PI, 0, Math.PI]}
                  scale={[1.08, 1.08, 1.06]}
                />
              </group>
            </group>
          </group>
          <OrthographicCamera name="1" makeDefault={true} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </>
  )
}
